### ISSUE TITLE
Chromatin Profile Enrichment object error

### ISSUE THREAD

**Issue by pinunQ** [FunctionLab/sei-manuscript#2]
Hi,

I ran your sei-framework and trained model on my own data which produced the results.

However, when I am running your sei-manuscript code to get the results in Chromatin_profiles_enrichment.py it shows some error that is based on object misposition.

Also I have two files in my chromatin-profiles-hdf5 (one for ref and other for alt) which should i use with row_labels.txt in order to run this code  completely?

The error log is pasted in the file below.

Thank you for your help.

Command A
`targets = h5py.File(TGTS_FILE, 'r')['targets']`

Command B
`targets = np.array(targets)[~targets_row_labels['contains_unk']]`
[error.log](https://github.com/FunctionLab/sei-manuscript/files/9119235/error.log)

**Comment by kathyxchen** [comment]
Hi! Sorry for the late response - the `chromatin_profiles_enrichment.py` is run on the target labels for the original input data in order to interpret / label the sequence classes, which is why your files will not be applicable to this enrichment script. Feel free to send me an email if you have more specific analysis you want to do with your predictions -- kc31@princeton.edu
